import fs from 'fs/promises';
import path from 'path';
import { Canvas } from '../builder/canvas.js';
import { ThemeComponent } from '../builder/component.js';

export class LiquidExporter {
  async export(outputDir: string): Promise<void> {
    const canvas = new Canvas();
    
    await fs.mkdir(path.join(outputDir, 'sections'), { recursive: true });
    await fs.mkdir(path.join(outputDir, 'snippets'), { recursive: true });
    await fs.mkdir(path.join(outputDir, 'layouts'), { recursive: true });

    await this.exportLayout(outputDir);

    for (const component of canvas.getComponents()) {
      await this.exportSection(component, outputDir);
    }

    await this.exportSnippets(outputDir);
  }

  private async exportLayout(outputDir: string): Promise<void> {
    const layout = `{% comment %}
  Theme Layout - Generated by Shopify Theme Forge
{% endcomment %}
<!doctype html>
<html class="no-js" lang="{{ request.locale.iso_code }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{{ page_title }}</title>
    {{ content_for_header }}
  </head>
  <body class="gradient">
    {% sections 'header-group' %}
    <main id="MainContent">
      {{ content_for_layout }}
    </main>
    {% sections 'footer-group' %}
  </body>
</html>
`;
    await fs.writeFile(path.join(outputDir, 'layout', 'theme.liquid'), layout);
  }

  private async exportSection(component: ThemeComponent, outputDir: string): Promise<void> {
    const liquid = this.generateSectionLiquid(component);
    const filename = `${component.type}-${component.name.toLowerCase().replace(/\s+/g, '-')}.liquid`;
    await fs.writeFile(path.join(outputDir, 'sections', filename), liquid);
  }

  private generateSectionLiquid(component: ThemeComponent): string {
    const sectionId = component.type.replace(/-/g, '_');
    
    return `{% comment %}
  Section: ${component.name}
  Type: ${component.type}
  Generated by Shopify Theme Forge
{% endcomment %}

<section class="section-${sectionId}" {{ shopify_attributes }}>
  <div class="container">
    {%- case sectionId -%}
    {%- when '${sectionId}' -%}
      ${this.generateSectionContent(component)}
    {%- endcase -%}
  </div>
</section>

{% schema %}
{
  "name": "${component.name}",
  "tag": "section",
  "class": "section-${sectionId}",
  "settings": [
    {
      "type": "text",
      "id": "title",
      "label": "Title"
    }
  ],
  "presets": [
    {
      "name": "${component.name}"
    }
  ]
}
{% endschema %}
`;
  }

  private generateSectionContent(component: ThemeComponent): string {
    switch (component.type) {
      case 'header':
        return `{% if section.settings.logo %}
  <img src="{{ section.settings.logo | image_url }}" alt="{{ shop.name }}">
{% endif %}
<h1>{{ shop.name }}</h1>`;
      case 'hero':
        return `{% if section.settings.title %}
  <h1>{{ section.settings.title }}</h1>
{% endif %}
{% if section.settings.subtitle %}
  <p>{{ section.settings.subtitle }}</p>
{% endif %}
{% if section.settings.cta_text %}
  <a href="{{ section.settings.cta_link }}">{{ section.settings.cta_text }}</a>
{% endif %}`;
      case 'product-grid':
        return `{% assign products = collections.all.products limit: section.settings.products_count %}
<div class="product-grid" style="--columns: {{ section.settings.columns }}">
  {% for product in products %}
    {% render 'product-card', product: product %}
  {% endfor %}
</div>`;
      default:
        return `<p>{{ section.settings.title }}</p>`;
    }
  }

  private async exportSnippets(outputDir: string): Promise<void> {
    const productCard = `{% comment %}
  Product Card Snippet
{% endcomment %}
<div class="product-card">
  {% if product.featured_image %}
    <a href="{{ product.url }}">
      <img src="{{ product.featured_image | image_url: width: 300 }}" 
           alt="{{ product.featured_image.alt | escape }}"
           loading="lazy">
    </a>
  {% endif %}
  <h3><a href="{{ product.url }}">{{ product.title }}</a></h3>
  <p>{{ product.price | money }}</p>
  {% if product.description %}
    <p>{{ product.description | truncate: 100 }}</p>
  {% endif %}
</div>
`;
    await fs.writeFile(path.join(outputDir, 'snippets', 'product-card.liquid'), productCard);
  }
}
